# Generated by Django 3.0.8 on 2021-04-09 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0004_datosscrapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosscrapy',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
