# Generated by Django 3.0.8 on 2021-04-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0006_remove_datosscrapy_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosscrapy',
            name='imagen',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
