# Generated by Django 3.0.8 on 2021-04-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0007_datosscrapy_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosscrapy',
            name='texto',
        ),
        migrations.AddField(
            model_name='datosscrapy',
            name='precio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosscrapy',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosscrapy',
            name='imagen',
            field=models.TextField(blank=True),
        ),
    ]
