# Generated by Django 3.0.8 on 2021-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0008_auto_20210410_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosscrapy',
            old_name='precio',
            new_name='precio_original',
        ),
        migrations.AddField(
            model_name='datosscrapy',
            name='precio_rebajado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
