# Generated by Django 3.0.8 on 2021-04-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0009_auto_20210410_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosscrapy',
            name='imagen',
            field=models.URLField(),
        ),
    ]
