# Generated by Django 3.0.8 on 2021-04-12 16:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0012_datosscrapy_informacion_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosscrapy',
            name='informacion_adicional',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
