# Generated by Django 3.0.8 on 2021-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0013_auto_20210412_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosscrapy',
            name='denominacion_de_origen',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
    ]
