# Generated by Django 3.0.8 on 2021-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0015_datosscrapy_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosscrapy',
            name='url',
            field=models.SlugField(default='titulo-prueba', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
