# Generated by Django 3.0.8 on 2021-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0018_datosscrapy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosscrapy',
            name='url',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
