# Generated by Django 3.0.8 on 2021-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0021_auto_20210421_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosscrapy',
            name='url_2',
        ),
        migrations.AddField(
            model_name='datosscrapy',
            name='url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
