# Generated by Django 3.0.8 on 2021-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0023_auto_20210421_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosscrapy',
            name='url',
            field=models.SlugField(max_length=255),
        ),
    ]
