# Generated by Django 3.0.8 on 2021-04-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0024_auto_20210421_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosscrapy',
            name='url',
        ),
        migrations.AddField(
            model_name='datosscrapy',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
