# Generated by Django 3.0.8 on 2021-04-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0025_auto_20210421_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosscrapy',
            name='slug',
        ),
    ]
