# Generated by Django 3.0.8 on 2021-05-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0027_datosscrapy_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasDatosScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miweb.DatosScrapy')),
            ],
        ),
    ]
