# Generated by Django 3.0.8 on 2021-05-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0028_categoriasdatosscrapy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriasdatosscrapy',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoriasdatosscrapy',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='datosscrapy',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miweb.CategoriasDatosScrapy'),
            preserve_default=False,
        ),
    ]
