# Generated by Django 3.0.8 on 2021-05-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0029_auto_20210504_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosscrapy',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriasDatosScrapy',
        ),
    ]
