# Generated by Django 3.0.8 on 2021-05-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0030_auto_20210504_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosscrapy',
            name='categoria',
            field=models.CharField(default='Ribera', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoriasDatosScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miweb.DatosScrapy', to_field='categoria')),
            ],
        ),
    ]
