# Generated by Django 3.0.8 on 2021-05-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0031_auto_20210504_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosscrapy',
            old_name='categoria',
            new_name='categoria_vinos',
        ),
    ]
