# Generated by Django 3.0.8 on 2021-05-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0032_auto_20210504_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriasdatosscrapy',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='datosscrapy',
            name='categoria_vinos',
        ),
    ]
