# Generated by Django 3.0.8 on 2021-05-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0033_auto_20210504_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriasDatosScrapy',
        ),
    ]
