# Generated by Django 3.0.8 on 2021-05-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0035_auto_20210504_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosscrapy',
            name='marca_vinos',
        ),
        migrations.DeleteModel(
            name='CategoriasDatosScrapy',
        ),
    ]
