# Generated by Django 3.0.8 on 2021-05-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0036_auto_20210504_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasDatosScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='datosscrapy',
            name='categoria',
            field=models.ForeignKey(default='Ribera', on_delete=django.db.models.deletion.CASCADE, to='miweb.CategoriasDatosScrapy', to_field='title'),
            preserve_default=False,
        ),
    ]
