# Generated by Django 3.0.8 on 2021-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0037_auto_20210504_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasdatosscrapy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
