# Generated by Django 3.0.8 on 2021-05-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0038_auto_20210504_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriasDatosScrapy',
            new_name='Categorias',
        ),
    ]
